### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: com/notnoop/apns/APNS

### ISSUE THREAD

**Issue by quanghoc** [aggarwalankush/push-notification-server#1]
After `mvn install`, I got this error:

```
java IOSPush
Exception in thread "main" java.lang.NoClassDefFoundError: com/notnoop/apns/APNS
    at IOSPush.main(IOSPush.java:16)
Caused by: java.lang.ClassNotFoundException: com.notnoop.apns.APNS
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 1 more

```

Any help?

**Comment by aggarwalankush** [comment]
Updated the instructions, you are no longer required to install maven. **Just clone the project and follow instructions for iOS or Android.**

Closing issue for now, please reopen if error still presists.
