### ISSUE TITLE
ios server not work

### ISSUE THREAD

**Issue by zqrl-sh** [aggarwalankush/push-notification-server#2]
When I run 'java  -cp apns.jar:. IOSPush'  and got a error :

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.RuntimeException: Invalid hex character: Y
        at com.notnoop.apns.internal.Utilities.charval(Utilities.java:125)
        at com.notnoop.apns.internal.Utilities.decodeHex(Utilities.java:112)
        at com.notnoop.apns.EnhancedApnsNotification.<init>(EnhancedApnsNotification.java:72)
        at com.notnoop.apns.internal.AbstractApnsService.push(AbstractApnsService.java:52)
        at com.notnoop.apns.internal.ApnsServiceImpl.push(ApnsServiceImpl.java:36)
        at IOSPush.main(IOSPush.java:26)

I run it  in webstorm terminal directly , the android push is fine

**Comment by zqrl-sh** [comment]
when import the org.slf4j.impl.StaticLoggerBinder it works
